### ISSUE TITLE
Integration with archiver/viewer

### ISSUE THREAD

**Issue by foxcpp** [bn4t/verteilzentrum#1]
What would be the appropriate way of integrating verteilzentrum (gezz, what a name) with some archival software?

The only ML functionality your project implements is list expansion and as I understood from README - it is all it is intended to do. 

I can imagine subscribing some meta-user (e.g. archiver@example.org) to all lists. Do you think it would be more convenient to have this as a configuration option?
E.g.
```
[[list]]
...
persistent_receivers = ["archiver@example.org"]
```

P.s. I was not able to open an issue on git.bn4t.org since registration is disabled.

**Comment by bn4t** [comment]
Uhh, this is embarrassing... for some reason I wasn't watching this repo and totally missed the two issues you created. 

The idea of a meta-user is an excellent idea. I think an archiver/viewer is a bit out of scope for verteilzentrum, however a meta-user fits it perfectly.

I'll probably be able to do this over the next couple days.

PS: verteilzentrum is german for distribution center (in the sense of postal distribution center), but I agree it's a hell of a word :)

**Comment by bn4t** [comment]
Regarding git.bn4t.me: I have decided to make Github the primary home of the project for sake of accessibility. Though I might move it to sourcehut at some point.
