### ISSUE TITLE
Sending messages via local MTA

### ISSUE THREAD

**Issue by foxcpp** [bn4t/verteilzentrum#2]
In current state, verte... eeh, ilzentrum is sending out messages directly to the MX of each recipient. This is not optimal as it fails to account for any (unfortunate) complexity of sending messages on the Internet.
For reference, [maddy](https://github.com/foxcpp/maddy)'s code for just sending messages is twice the whole code base of this project (1576 sLoC, 3479 sLoC with tests).  

I propose reconsidering that part of the project and delegate handling of this chaos to a complete MTA.]
This will make it even more "KISS", after all :)

**Comment by bn4t** [comment]
Yeah, the built-in mta is definitely not ideal, especially since a lot of things are not implemented.

I'm going to change this to the solution proposed by you. Also like you mentioned, this makes the project even more KISS :)
